//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHTraiCay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.HoaDonChiTiets = new HashSet<HoaDonChiTiet>();
        }
    
        public int ID { get; set; }
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string DVT { get; set; }
        public string QuyCach { get; set; }
        public string MoTa { get; set; }
        public string TenHinh { get; set; }
        public int GiaBan { get; set; }
        public Nullable<int> GiaThiTruong { get; set; }
        public int LoaiID { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
        public string XuatXu { get; set; }
        public int TinhTrang { get; set; }
    
        public virtual Loai Loai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiets { get; set; }
    }
}
